const { Configuration, OpenAIApi } = require("openai");
const sample_output = require("../sample_output.json");
require("dotenv").config();

const openAiConversation = async (gptPrompots) => {
  const configuration = new Configuration({
    apiKey: process.env.OPENAI_API_KEY,
  });
  const openai = new OpenAIApi(configuration);

  const messages = [];
  messages.push(
    "I have an array of objects of best practices with index and best_practices as the keys. Iterate over all the best practices. Find similar best practices and club it together in one string with + sign and make key as practice and also make index as an array with key name as citations of the clubbed strings. I will provide you the object in next message. I only need the output not the code."
  );
  messages.push(JSON.stringify(gptPrompots));

  console.log(messages);

  try {
    const completion = await openai.createChatCompletion({
      model: "gpt-3.5-turbo",
      messages: messages,
    });

    const completion_text = completion.data.choices[0].message.content;
    return completion_text;
  } catch (error) {
    // SInce we dont have api key configured I am returning the sample output generated by asking
    // question from chatgpt
    return sample_output;
  }
};

module.exports = openAiConversation;
